name: Enable auto-merge for scontainit PRs

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.actor == 'scontainit'
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.SCONTAIN_GOLANG_PAT }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.SCONTAIN_GOLANG_PAT }}
          PR_URL: ${{ github.event.pull_request.html_url }}